Repository openstack-k8s-operators/horizon-operator, pull requests merged in 2024-02, with the labels that each got.

#280 Tweak probe timing
  pkg/horizon/deployment.go
Labels: approved, lgtm

#279 Drop Debug fields
  README.md
  api/bases/horizon.openstack.org_horizons.yaml
  api/v1beta1/horizon_types.go
  api/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/horizon.openstack.org_horizons.yaml
Labels: approved, lgtm

#275 This change adds requirements for FIPS
  .prow_ci.env
  Dockerfile
  Makefile
  config/manifests/bases/horizon-operator.clusterserviceversion.yaml
Labels: approved, lgtm

#281 Controller runtime update
  .ci-operator.yaml
  .github/workflows/build-horizon-operator.yaml
  Dockerfile
  api/bases/horizon.openstack.org_horizons.yaml
  api/go.mod
  api/go.sum
  api/v1beta1/horizon_webhook.go
  config/crd/bases/horizon.openstack.org_horizons.yaml
  controllers/horizon_controller.go
  go.mod
  go.sum
  main.go
  tests/functional/suite_test.go
Labels: approved

#283 Controller runtime v0.16.4 Go 1.20
  .ci-operator.yaml
  .github/workflows/build-horizon-operator.yaml
  Dockerfile
  api/bases/horizon.openstack.org_horizons.yaml
  api/go.mod
  api/go.sum
  api/v1beta1/horizon_webhook.go
  config/crd/bases/horizon.openstack.org_horizons.yaml
  controllers/horizon_controller.go
  go.mod
  go.sum
  main.go
  tests/functional/suite_test.go
Labels: approved

#285 Unique LeaderElectionID
  main.go
Labels: approved

#288 Bump golangci-lint version
  .ci-operator.yaml
  .golangci.yaml
  .pre-commit-config.yaml
Labels: approved

#290 [renovate]Remove golang constraint
  renovate.json
Labels: approved, lgtm

#287 Sync EnvTest version with k8s version
  Makefile
Labels: approved, lgtm

#286 add kuttl test to check dashboard reachability
  tests/kuttl/common/assert-sample-deployment.yaml
Labels: approved, lgtm, ok-to-test

#296 Regenerate go.mod indirect dependencies
  api/go.mod
  api/go.sum
  go.mod
  go.sum
Labels: approved, lgtm
